/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Root
         * @description Root endpoint.
         */
        get: operations["root__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/cases": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Cases Endpoint
         * @description Get all cases with pagination, filtering and sorting.
         *
         *     Query Parameters:
         *     - page: Page number (0-indexed, default: 0)
         *     - pageSize: Number of items per page (default: 25)
         *     - sortBy: Field to sort by (default: createdAt)
         *     - sortOrder: Sort order - 'asc' or 'desc' (default: desc)
         *     - view: Preset view filter - 'my-cases', 'all-cases', or 'sla-breaches'
         *     - search: Free-text search on entity name or case ID
         *     - case_status: Filter by case status
         *     - businessUnit: Filter by business unit
         *     - assignedUser: Filter by assigned user
         */
        get: operations["list_cases_endpoint_api_cases_get"];
        put?: never;
        /**
         * Create Case Endpoint
         * @description Create a new case.
         */
        post: operations["create_case_endpoint_api_cases_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/cases/{case_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Case Endpoint
         * @description Get a case by ID.
         */
        get: operations["get_case_endpoint_api_cases__case_id__get"];
        /**
         * Update Case Endpoint
         * @description Update an existing case.
         */
        put: operations["update_case_endpoint_api_cases__case_id__put"];
        post?: never;
        /**
         * Delete Case Endpoint
         * @description Delete a case.
         */
        delete: operations["delete_case_endpoint_api_cases__case_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/cases/{case_id}/convert-to-pas": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Convert To Pas Endpoint
         * @description Convert a case to PAS Client Process format.
         *
         *     This endpoint retrieves a case and converts it to the downstream
         *     PAS (Process Automation System) schema format.
         */
        post: operations["convert_to_pas_endpoint_api_cases__case_id__convert_to_pas_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/cases/{case_id}/send-to-pas": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Send To Pas Endpoint
         * @description Convert a case to PAS format and send to downstream processing queue.
         *
         *     This endpoint:
         *     1. Retrieves the case
         *     2. Converts it to PAS Client Process format
         *     3. Sends it to the processing queue for downstream automation
         *
         *     The case will be added to the queue with the specified priority.
         */
        post: operations["send_to_pas_endpoint_api_cases__case_id__send_to_pas_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * Address
         * @description Address information.
         */
        Address: {
            /** Line1 */
            line1: string;
            /** Line2 */
            line2?: string | null;
            /** City */
            city: string;
            /** Postcode */
            postCode: string;
            /** Country */
            country?: string | null;
        };
        /**
         * Attachment
         * @description Case attachment.
         */
        Attachment: {
            /** Id */
            id: string;
            /** Filename */
            fileName: string;
            fileType: components["schemas"]["FileType"];
            source: components["schemas"]["AttachmentSource"];
            /** Uploadedat */
            uploadedAt: string;
            /** Uploadedby */
            uploadedBy?: string | null;
            /** Downloadurl */
            downloadUrl: string;
            /** Lastupdatedat */
            lastUpdatedAt: string;
        };
        /**
         * AttachmentSource
         * @description Source of attachment.
         * @enum {string}
         */
        AttachmentSource: "manual" | "ch" | "fca" | "db" | "ln" | "email";
        /**
         * AutomationResults
         * @description Container for all automation results.
         */
        "AutomationResults-Input": {
            companiesHouse: components["schemas"]["CompaniesHouseResult-Input"];
            fca: components["schemas"]["FCAResult-Input"];
            dAndB: components["schemas"]["DAndBResult-Input"];
            lexisNexis: components["schemas"]["LexisNexisResult-Input"];
        };
        /**
         * AutomationResults
         * @description Container for all automation results.
         */
        "AutomationResults-Output": {
            companiesHouse: components["schemas"]["CompaniesHouseResult-Output"];
            fca: components["schemas"]["FCAResult-Output"];
            dAndB: components["schemas"]["DAndBResult-Output"];
            lexisNexis: components["schemas"]["LexisNexisResult-Output"];
        };
        /**
         * AutomationStatus
         * @description Status of automation results.
         * @enum {string}
         */
        AutomationStatus: "success" | "not_applicable" | "failed" | "pending";
        /**
         * BEFormData
         * @description BE Form Data for case.
         */
        BEFormData: {
            /** Legalname */
            legalName: string;
            /** Tradingname */
            tradingName: string;
            /** Country */
            country: string;
            /** Roletype */
            roleType: string;
            /** Addressline1 */
            addressLine1: string;
            /** Addressline2 */
            addressLine2?: string | null;
            /** City */
            city: string;
            /** Postcode */
            postcode: string;
            /** Registrationnumber */
            registrationNumber: string;
            customerType: components["schemas"]["CustomerType"];
            /** Cpiscore */
            cpiScore?: number | null;
            /**
             * Statementemail
             * Format: email
             */
            statementEmail: string;
            /**
             * Creditcontrolleremail
             * Format: email
             */
            creditControllerEmail: string;
            /** Bankname */
            bankName?: string | null;
            /** Bankaccountnumber */
            bankAccountNumber?: string | null;
            /** Banksortcode */
            bankSortCode?: string | null;
            /** Bankdetailsrequired */
            bankDetailsRequired: boolean;
        };
        /**
         * BankDetails
         * @description Bank account details.
         */
        BankDetails: {
            /** Type */
            type?: string | null;
            /** Bank Name */
            bank_name?: string | null;
            /** Bank Account Name */
            bank_account_name?: string | null;
            /** Swift Code */
            swift_code?: string | null;
            /** Sort Code */
            sort_code?: string | null;
            /** Aba */
            aba?: string | null;
            /** Iban */
            iban?: string | null;
            /** Account Number */
            account_number?: string | null;
            /** Currency */
            currency?: string | null;
            /** Bank Country */
            bank_country?: string | null;
        };
        /**
         * CaseCreate
         * @description Model for creating a case (without ID).
         */
        CaseCreate: {
            /** Entityname */
            entityName: string;
            /** @default ONBOARDING_COMPLETE */
            status: components["schemas"]["CaseStatus"];
            riskTier: components["schemas"]["RiskTier"];
            /** Cpiscore */
            cpiScore?: number | null;
            /** Assigneduser */
            assignedUser: string;
            /** Businessunit */
            businessUnit: string;
            beForm: components["schemas"]["BEFormData"];
            automationResults: components["schemas"]["AutomationResults-Input"];
            /**
             * Attachments
             * @default []
             */
            attachments: components["schemas"]["Attachment"][];
        };
        /**
         * CaseDetail
         * @description Complete case detail (GET /case/:id response).
         */
        CaseDetail: {
            /** Id */
            _id: string;
            /** Entityname */
            entityName: string;
            status: components["schemas"]["CaseStatus"];
            riskTier: components["schemas"]["RiskTier"];
            /** Cpiscore */
            cpiScore?: number | null;
            /** Daysopen */
            daysOpen?: number | null;
            /** Createdat */
            createdAt: string;
            /** Lastupdated */
            lastUpdated: string;
            /** Assigneduser */
            assignedUser: string;
            /** Businessunit */
            businessUnit: string;
            beForm: components["schemas"]["BEFormData"];
            automationResults: components["schemas"]["AutomationResults-Output"];
            /**
             * Attachments
             * @default []
             */
            attachments: components["schemas"]["Attachment"][];
        };
        /**
         * CaseListItem
         * @description Case list item (for GET /cases response).
         */
        CaseListItem: {
            /** Id */
            id: string;
            /** Entityname */
            entityName: string;
            riskTier: components["schemas"]["RiskTier"];
            /** Assigneduser */
            assignedUser: string;
            status: components["schemas"]["CaseStatus"];
            /** Businessunit */
            businessUnit: string;
            /** Roletype */
            roleType: string;
            /** Daysopen */
            daysOpen?: number | null;
            /** Dayssincelastcustomertouchpoint */
            daysSinceLastCustomerTouchpoint?: number | null;
            /** Lastupdated */
            lastUpdated: string;
            /** Createdat */
            createdAt: string;
        };
        /**
         * CaseStatus
         * @description Case workflow status.
         * @enum {string}
         */
        CaseStatus: "ONBOARDING_COMPLETE" | "AUTOMATION_IN_PROGRESS" | "AWAITING_KYC_REVIEW" | "AWAITING_EXTERNAL_RESPONSE" | "FINANCIAL_CRIME_REVIEW" | "READY_KYC_MANAGER_REVIEW" | "DIVISIONAL_APPROVAL_LOW_RISK" | "DIVISIONAL_APPROVAL_HIGH_RISK" | "AWAITING_SECURITY_COMMITTEE" | "READY_FOR_PAS" | "CREATED_IN_PAS" | "COMPLETED" | "REJECTED";
        /**
         * CasesListResponse
         * @description Paginated case list response.
         */
        CasesListResponse: {
            /** Content */
            content: components["schemas"]["CaseListItem"][];
            /** Totalelements */
            totalElements: number;
            /** Page */
            page: number;
            /** Pagesize */
            pageSize: number;
        };
        /**
         * CompaniesHouseData
         * @description Companies House automation data.
         */
        CompaniesHouseData: {
            /** Legalentityname */
            legalEntityName: string;
            /** Registrationnumber */
            registrationNumber: string;
            /** Registeredaddress */
            registeredAddress: string;
            /** Status */
            status: string;
            /** Dissolvedon */
            dissolvedOn?: string | null;
            /** Type */
            type: string;
            /** Incorporatedon */
            incorporatedOn: string;
            /** Accounts */
            accounts: string;
            /** Confirmationstatement */
            confirmationStatement: string;
            /** Natureofbusiness */
            natureOfBusiness: string[];
            /** Directors */
            directors: components["schemas"]["CompaniesHouseDirector"][];
            /** Documents */
            documents: components["schemas"]["CompaniesHouseDocument"][];
            /** Externalurl */
            externalUrl?: string | null;
        };
        /**
         * CompaniesHouseDirector
         * @description Companies House director information.
         */
        CompaniesHouseDirector: {
            /** Name */
            name: string;
            /** Address */
            address: string;
            /** Status */
            status: string;
        };
        /**
         * CompaniesHouseDocument
         * @description Companies House document.
         */
        CompaniesHouseDocument: {
            /** Id */
            id: string;
            /** Filename */
            fileName: string;
            /** Type */
            type: string;
            /** Url */
            url: string;
        };
        /**
         * CompaniesHouseResult
         * @description Companies House automation result.
         */
        "CompaniesHouseResult-Input": {
            status: components["schemas"]["AutomationStatus"];
            data?: components["schemas"]["CompaniesHouseData"] | null;
            /** Message */
            message?: string | null;
        };
        /**
         * CompaniesHouseResult
         * @description Companies House automation result.
         */
        "CompaniesHouseResult-Output": {
            status: components["schemas"]["AutomationStatus"];
            data?: components["schemas"]["CompaniesHouseData"] | null;
            /** Message */
            message?: string | null;
        };
        /**
         * CustomerType
         * @description Customer size classification.
         * @enum {string}
         */
        CustomerType: "Micro" | "Small" | "Medium" | "Large" | "Consumer";
        /**
         * DAndBData
         * @description D&B automation data.
         */
        DAndBData: {
            /** Dunsnumber */
            dunsNumber: string;
            /** Legalname */
            legalName: string;
            registeredAddress: components["schemas"]["Address"];
            /** Principalinformation */
            principalInformation: components["schemas"]["DAndBPrincipal"][];
            /** Shareholding */
            shareholding: components["schemas"]["DAndBShareholder"][];
            /** Ubo */
            ubo?: string | null;
            /** Lastupdated */
            lastUpdated: string;
        };
        /**
         * DAndBPrincipal
         * @description D&B principal information.
         */
        DAndBPrincipal: {
            /** Name */
            name: string;
            /** Title */
            title: string;
        };
        /**
         * DAndBResult
         * @description D&B automation result.
         */
        "DAndBResult-Input": {
            status: components["schemas"]["AutomationStatus"];
            data?: components["schemas"]["DAndBData"] | null;
            /** Message */
            message?: string | null;
        };
        /**
         * DAndBResult
         * @description D&B automation result.
         */
        "DAndBResult-Output": {
            status: components["schemas"]["AutomationStatus"];
            data?: components["schemas"]["DAndBData"] | null;
            /** Message */
            message?: string | null;
        };
        /**
         * DAndBShareholder
         * @description D&B shareholder information.
         */
        DAndBShareholder: {
            /** Name */
            name: string;
            /** Percentageowned */
            percentageOwned: number;
        };
        /**
         * FCAAdditionalInformation
         * @description FCA additional information.
         */
        FCAAdditionalInformation: {
            /** Appointedrepresentatives */
            appointedRepresentatives: string[];
            /** Keyindividuals */
            keyIndividuals: components["schemas"]["FCAKeyIndividual"][];
            /** Passportingrights */
            passportingRights: string[];
            /** Tradingnames */
            tradingNames: string[];
        };
        /**
         * FCAData
         * @description FCA automation data.
         */
        "FCAData-Input": {
            /** Frn */
            frn: string;
            /** Organisationname */
            organisationName: string;
            /** Status */
            status: string;
            /** Effectivedate */
            effectiveDate: string;
            /** Businesstype */
            businessType: string;
            /** Clientmoneypermissions */
            clientMoneyPermissions: boolean;
            /** Psdagentstatus */
            psdAgentStatus: string;
            /** Psdemdstatus */
            psdEmdStatus: string;
            /** Authorisedactivities */
            authorisedActivities: string[];
            registeredAddress: components["schemas"]["Address"];
            regulatoryInformation: components["schemas"]["FCARegulatoryInformation"];
            additionalInformation: components["schemas"]["FCAAdditionalInformation"];
            /** Lastupdated */
            lastUpdated: string;
            /** Externalurl */
            externalUrl?: string | null;
        };
        /**
         * FCAData
         * @description FCA automation data.
         */
        "FCAData-Output": {
            /** Frn */
            frn: string;
            /** Organisationname */
            organisationName: string;
            /** Status */
            status: string;
            /** Effectivedate */
            effectiveDate: string;
            /** Businesstype */
            businessType: string;
            /** Clientmoneypermissions */
            clientMoneyPermissions: boolean;
            /** Psdagentstatus */
            psdAgentStatus: string;
            /** Psdemdstatus */
            psdEmdStatus: string;
            /** Authorisedactivities */
            authorisedActivities: string[];
            registeredAddress: components["schemas"]["Address"];
            regulatoryInformation: components["schemas"]["FCARegulatoryInformation"];
            additionalInformation: components["schemas"]["FCAAdditionalInformation"];
            /** Lastupdated */
            lastUpdated: string;
            /** Externalurl */
            externalUrl?: string | null;
        };
        /**
         * FCAKeyIndividual
         * @description FCA key individual.
         */
        FCAKeyIndividual: {
            /** Name */
            name: string;
            /** Roles */
            roles: string[];
        };
        /**
         * FCARegulatoryInformation
         * @description FCA regulatory information.
         */
        FCARegulatoryInformation: {
            /** Regulators */
            regulators: string;
            /** Requirements */
            requirements: string;
            /** Waivers */
            waivers: string;
            /** Exclusions */
            exclusions: string;
            /** Disciplinaryhistory */
            disciplinaryHistory: string;
        };
        /**
         * FCAResult
         * @description FCA automation result.
         */
        "FCAResult-Input": {
            status: components["schemas"]["AutomationStatus"];
            data?: components["schemas"]["FCAData-Input"] | null;
            /** Message */
            message?: string | null;
        };
        /**
         * FCAResult
         * @description FCA automation result.
         */
        "FCAResult-Output": {
            status: components["schemas"]["AutomationStatus"];
            data?: components["schemas"]["FCAData-Output"] | null;
            /** Message */
            message?: string | null;
        };
        /**
         * FileType
         * @description Attachment file types.
         * @enum {string}
         */
        FileType: "PDF" | "DOC" | "DOCX" | "CSV" | "XLSX" | "MSG";
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * LexisNexisFinCrimeApproval
         * @description Financial Crime approval for LexisNexis match.
         */
        LexisNexisFinCrimeApproval: {
            /** Approvedby */
            approvedBy: string;
            /** Approvedat */
            approvedAt: string;
            /**
             * Status
             * @enum {string}
             */
            status: "approved" | "rejected";
        };
        /**
         * LexisNexisMatch
         * @description LexisNexis sanction/PEP match.
         */
        LexisNexisMatch: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /**
             * Type
             * @enum {string}
             */
            type: "company" | "individual";
            /** Matchscore */
            matchScore: number;
            /** Sourcename */
            sourceName: string;
            /** Countries */
            countries: string[];
            /** Reasonlisted */
            reasonListed: string;
            /** Comments */
            comments: string;
            /** Dateofbirth */
            dateOfBirth?: string | null;
            resolution: components["schemas"]["LexisNexisResolution"];
            /** Resolutionnote */
            resolutionNote?: string | null;
            /** Resolvedby */
            resolvedBy?: string | null;
            /** Resolvedat */
            resolvedAt?: string | null;
            finCrimeApproval?: components["schemas"]["LexisNexisFinCrimeApproval"] | null;
        };
        /**
         * LexisNexisResolution
         * @description LexisNexis match resolution status.
         * @enum {string}
         */
        LexisNexisResolution: "pending" | "discounted" | "accepted" | "escalated";
        /**
         * LexisNexisResult
         * @description LexisNexis automation result.
         */
        "LexisNexisResult-Input": {
            status: components["schemas"]["AutomationStatus"];
            /** Data */
            data?: components["schemas"]["LexisNexisMatch"][] | null;
            /** Message */
            message?: string | null;
        };
        /**
         * LexisNexisResult
         * @description LexisNexis automation result.
         */
        "LexisNexisResult-Output": {
            status: components["schemas"]["AutomationStatus"];
            /** Data */
            data?: components["schemas"]["LexisNexisMatch"][] | null;
            /** Message */
            message?: string | null;
        };
        /**
         * PASClientProcess
         * @description PAS Client Process schema model.
         */
        PASClientProcess: {
            /**
             * Process
             * @default CLIENT
             */
            process: string;
            /** Extractionid */
            extractionId: string;
            /** Multidivision */
            multidivision: boolean;
            /**
             * Senttorpaby
             * Format: email
             */
            sentToRpaBy: string;
            /**
             * Statementemail
             * Format: email
             */
            statementEmail: string;
            /** Entityname */
            entityName: string;
            /** Businessortradingname */
            businessOrTradingName: string;
            /** System */
            system: string;
            /** Requestedby */
            requestedBy: string;
            /** Businessunit */
            businessUnit: string;
            /**
             * Dateuploaded
             * Format: date
             */
            dateUploaded: string;
            /**
             * Reviewdate
             * Format: date
             */
            reviewDate: string;
            /** Accountroletype */
            accountRoleType: string;
            /** Requestpurpose */
            requestPurpose: string;
            /** Accountreference */
            accountReference?: string | null;
            toba: components["schemas"]["TOBA"];
            /** Territorycode */
            territoryCode: string;
            /** Addresses */
            addresses: components["schemas"]["Address"][];
            /** Bankdetails */
            bankDetails: components["schemas"]["BankDetails"][];
            /** Customertype */
            customerType: string;
            /** Regulationstatus */
            regulationStatus: string;
            /** Status */
            status: string;
            /** Fcareference */
            fcaReference?: string | null;
            /** Subcategory */
            subcategory?: string | null;
            /** Note */
            note?: string | null;
            /** Changetype */
            changeType?: string | null;
        };
        /**
         * RiskTier
         * @description Risk tier classification.
         * @enum {string}
         */
        RiskTier: "Higher Risk" | "Lower Risk";
        /**
         * TOBA
         * @description Terms of Business Agreement.
         */
        TOBA: {
            /**
             * Dateagreedsent
             * Format: date
             */
            dateAgreedSent: string;
            /** Tobatype */
            tobaType: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    root__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    list_cases_endpoint_api_cases_get: {
        parameters: {
            query?: {
                /** @description Page number (0-indexed) */
                page?: number;
                /** @description Page size */
                pageSize?: number;
                /** @description Field to sort by */
                sortBy?: string;
                /** @description Sort order */
                sortOrder?: string;
                /** @description View filter: my-cases, all-cases, sla-breaches */
                view?: string | null;
                /** @description Search entity name or case ID */
                search?: string | null;
                /** @description Filter by case status */
                case_status?: string | null;
                /** @description Filter by business unit */
                businessUnit?: string | null;
                /** @description Filter by assigned user */
                assignedUser?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CasesListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_case_endpoint_api_cases_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CaseCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_case_endpoint_api_cases__case_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                case_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CaseDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_case_endpoint_api_cases__case_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                case_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CaseCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_case_endpoint_api_cases__case_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                case_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    convert_to_pas_endpoint_api_cases__case_id__convert_to_pas_post: {
        parameters: {
            query?: {
                /** @description Email of RPA sender */
                sentToRpaBy?: string;
            };
            header?: never;
            path: {
                case_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PASClientProcess"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    send_to_pas_endpoint_api_cases__case_id__send_to_pas_post: {
        parameters: {
            query?: {
                /** @description Email of RPA sender */
                sentToRpaBy?: string;
                /** @description Queue priority: High, Medium, Low */
                priority?: string;
                /** @description Reference prefix */
                referencePrefix?: string;
            };
            header?: never;
            path: {
                case_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
